[package]
name = "stardb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-multipart = "0.6.0"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
actix-web = "4.3.1"
chrono = { version = "0.4.26", features = ["serde"] }
csv = "1.2.2"
dotenv_codegen = "0.15.0"
env_logger = "0.10.0"
lettre = { version = "0.10.4", features = ["tokio1-native-tls"] }
linked-hash-map = "0.5.6"
log = "0.4.19"
rand = "0.8.5"
regex = "1.9.1"
reqwest = { version = "0.11.18", features = ["json"] }
rust-argon2 = "1.0.0"
serde = { version = "1.0.173", features = ["derive"] }
serde_json = "1.0.103"
sqlx = { version = "0.7.1", features = [
    "postgres",
    "chrono",
    "uuid",
    "runtime-tokio-native-tls",
] }
strum = { version = "0.25.0", features = ["derive"] }
utoipa = { version = "3.3.0", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "3.1.4", features = ["actix-web"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
