[package]
name = "stardb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-multipart = "0.6.1"
actix-session = "0.8.0"
actix-web = "4.4.0"
anyhow = "1.0.75"
async-rwlock = "1.3.0"
async-trait = "0.1.74"
calamine = "0.22.1"
chrono = { version = "0.4.31", features = ["serde"] }
csv = "1.3.0"
dotenv = "0.15.0"
env_logger = "0.10.0"
futures = "0.3.29"
image = "0.24.7"
indexmap = "2.1.0"
lazy_static = "1.4.0"
lettre = { version = "0.11.1", features = ["tokio1-native-tls"] }
log = "0.4.20"
quick-xml = { version = "0.31.0", features = ["serialize"] }
rand = "0.8.5"
regex = "1.10.2"
reqwest = { version = "0.11.22", features = ["json"] }
rust-argon2 = "2.0.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
sqlx = { version = "0.7.2", features = [
    "postgres",
    "chrono",
    "uuid",
    "runtime-tokio-native-tls",
] }
strum = { version = "0.25.0", features = ["derive"] }
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
url = "2.4.1"
utoipa = { version = "4.0.0", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "4.0.0", features = ["actix-web"] }
uuid = { version = "1.5.0", features = ["v4", "serde"] }
walkdir = "2.4.0"
webp = "0.2.6"
