[package]
name = "stardb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-multipart = "0.7.2"
actix-session = "0.10.0"
actix-web = "4.8.0"
anyhow = "1.0.86"
async-process = "2.2.3"
async-rwlock = "1.3.0"
calamine = "0.25.0"
chrono = { version = "0.4.38", features = ["serde"] }
csv = "1.3.0"
dotenv = "0.15.0"
futures = "0.3.30"
image = "0.25.2"
indexmap = "2.3.0"
lazy_static = "1.5.0"
lettre = { version = "0.11.7", default-features = false, features = [
  "tokio1-rustls-tls",
  "builder",
  "smtp-transport",
] }
quick-xml = { version = "0.36.1", features = ["serialize"] }
rand = "0.8.5"
regex = "1.10.6"
reqwest = { version = "0.12.5", default-features = false, features = [
  "json",
  "rustls-tls",
] }
rust-argon2 = "2.1.0"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
sqlx = { version = "0.8.0", features = [
  "postgres",
  "chrono",
  "uuid",
  "runtime-tokio-rustls",
] }
strum = { version = "0.26.3", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.2"
utoipa = { version = "4.2.3", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["actix-web", "reqwest"] }
uuid = { version = "1.10.0", features = ["v4", "serde"] }
walkdir = "2.5.0"
webp = "0.3.0"
