[package]
name = "stardb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-multipart = "0.6.2"
actix-session = "0.9.0"
actix-web = "4.7.0"
anyhow = "1.0.86"
async-process = "2.2.3"
async-rwlock = "1.3.0"
calamine = "0.25.0"
chrono = { version = "0.4.38", features = ["serde"] }
csv = "1.3.0"
dotenv = "0.15.0"
futures = "0.3.30"
image = "0.25.1"
indexmap = "2.2.6"
lazy_static = "1.4.0"
lettre = { version = "0.11.7", features = ["tokio1-native-tls"] }
quick-xml = { version = "0.32.0", features = ["serialize"] }
rand = "0.8.5"
regex = "1.10.5"
reqwest = { version = "0.12.4", features = ["json"] }
rust-argon2 = "2.1.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
sqlx = { version = "0.7.4", features = [
  "postgres",
  "chrono",
  "uuid",
  "runtime-tokio-native-tls",
] }
strum = { version = "0.26.2", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.1"
utoipa = { version = "4.2.3", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["actix-web", "reqwest"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
walkdir = "2.5.0"
webp = "0.3.0"
