[package]
name = "stardb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.5"
actix-multipart = "0.6.1"
actix-session = "0.9.0"
actix-web = "4.5.1"
anyhow = "1.0.80"
async-rwlock = "1.3.0"
calamine = "0.24.0"
chrono = { version = "0.4.34", features = ["serde"] }
csv = "1.3.0"
dotenv = "0.15.0"
futures = "0.3.30"
image = "0.24.9"
indexmap = "2.2.3"
lazy_static = "1.4.0"
lettre = { version = "0.11.4", features = ["tokio1-native-tls"] }
quick-xml = { version = "0.31.0", features = ["serialize"] }
rand = "0.8.5"
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["json"] }
rust-argon2 = "2.1.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sqlx = { version = "0.7.3", features = [
    "postgres",
    "chrono",
    "uuid",
    "runtime-tokio-native-tls",
] }
strum = { version = "0.26.1", features = ["derive"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.0"
utoipa = { version = "4.2.0", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["actix-web"] }
uuid = { version = "1.7.0", features = ["v4", "serde"] }
walkdir = "2.4.0"
webp = "0.2.6"
