[package]
name = "stardb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.5"
actix-multipart = "0.6.1"
actix-session = "0.9.0"
actix-web = "4.4.1"
anyhow = "1.0.79"
async-rwlock = "1.3.0"
calamine = "0.23.1"
chrono = { version = "0.4.33", features = ["serde"] }
csv = "1.3.0"
dotenv = "0.15.0"
env_logger = "0.11.1"
futures = "0.3.30"
image = "0.24.8"
indexmap = "2.2.2"
lazy_static = "1.4.0"
lettre = { version = "0.11.4", features = ["tokio1-native-tls"] }
log = "0.4.20"
quick-xml = { version = "0.31.0", features = ["serialize"] }
rand = "0.8.5"
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["json"] }
rust-argon2 = "2.1.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
sqlx = { version = "0.7.3", features = [
    "postgres",
    "chrono",
    "uuid",
    "runtime-tokio-native-tls",
] }
strum = { version = "0.26.1", features = ["derive"] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
url = "2.5.0"
utoipa = { version = "4.2.0", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["actix-web"] }
uuid = { version = "1.7.0", features = ["v4", "serde"] }
walkdir = "2.4.0"
webp = "0.2.6"
