[package]
name = "stardb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.3.1"
chrono = { version = "0.4.26", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.10.0"
jsonwebtoken = "8.3.0"
lettre = { version = "0.10.4", features = ["tokio1-native-tls"] }
log = "0.4.19"
rand = "0.8.5"
regex = "1.8.4"
reqwest = { version = "0.11.18", features = ["json"] }
rust-argon2 = "1.0.0"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.99"
sqlx = { version = "0.7.0", features = [
    "postgres",
    "chrono",
    "runtime-tokio-native-tls",
] }
strum = { version = "0.25.0", features = ["derive"] }
utoipa = { version = "3.3.0", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "3.1.3", features = ["actix-web"] }
uuid = { version = "1.4.0", features = ["v4", "serde"] }
