[package]
name = "stardb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-multipart = "0.6.0"
actix-session = "0.7.2"
actix-web = "4.3.1"
anyhow = "1.0.75"
async-trait = "0.1.73"
chrono = { version = "0.4.26", features = ["serde"] }
csv = "1.2.2"
dotenv = "0.15.0"
env_logger = "0.10.0"
futures = "0.3.28"
indexmap = "2.0.0"
lettre = { version = "0.10.4", features = ["tokio1-native-tls"] }
log = "0.4.20"
rand = "0.8.5"
regex = "1.9.3"
reqwest = { version = "0.11.18", features = ["json"] }
rust-argon2 = "2.0.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
sqlx = { version = "0.7.1", features = [
    "postgres",
    "chrono",
    "uuid",
    "runtime-tokio-native-tls",
] }
strum = { version = "0.25.0", features = ["derive"] }
utoipa = { version = "3.4.4", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "3.1.5", features = ["actix-web"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
