name: Clippy

on: pull_request

jobs:
  deploy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
